# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=senha123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/help_desk
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# CORS configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200

# JWT configuration
smallrye.jwt.sign.key.location=private_key.pem
smallrye.jwt.verify.key.location=public_key.pem

# JWT to accept using cookies instead of headers
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=jwt

# Doc
quarkus.smallrye-openapi.path=/doc
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.info-title=Help Desk API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=\
  RESTful API for a Help Desk ticketing system designed to manage technical support requests. \
  It provides endpoints for creating, retrieving, updating, and closing tickets, with support \
  for status tracking, priority management, and ticket history.
quarkus.smallrye-openapi.info-contact-email=fabio.hkcesare@outlook.com
quarkus.smallrye-openapi.info-contact-url=https://github.com/FabioKuriki
quarkus.swagger-ui.filter=true
